server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:SimpleProgramming/springcloud-config-repository.git
          ignore-local-ssh-settings: true
          strict-host-key-checking: false
          search-paths:
          - configuration/{application}/
          - configuration/
          private-key: |
                        -----Your Private Key-----
                        
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8700/eureka/                                 